### ISSUE TITLE
0.8.0 release in operatorhub / OpenShift without any release here on GitHub?

### ISSUE THREAD

**Issue by BGrasnick** [argoproj-labs/argocd-operator#1077]
**Describe the bug**
Without any release here on GitHub, there is a new release 0.8.0 in operatorhub: https://operatorhub.io/operator/argocd-operator and therefore also in OpenShift itself

**Expected behavior**
Releases should be consistent and made here as well as on operatorhub.
We subscribed to the releases here to be kept up to date and where surprised about the new release in OpenShift...

**Comment by iam-veeramalla** [comment]
Hi @BGrasnick , I just realised this morning that the tag was not created in this repo.

Sorry for the inconvenience. I will make sure that this does not happen going forward.

**Comment by svghadi** [comment]
v0.8.0 is out now. Release notes can be found at https://github.com/argoproj-labs/argocd-operator/releases/tag/v0.8.0

**Comment by saumeya** [comment]
Can this be closed?
