### ISSUE TITLE
ArgoCD OutOfSync: sync loop due to 0.5CPU vs 500mCPU

### ISSUE THREAD

**Issue by 4TT1L4** [argoproj-labs/argocd-operator#1290]
**Describe the bug**
ArgoCD detects configuration differences and it is attempting to sync when the limit and request are defined in mCPU units.

ArgoCD won't realize that 0.5 CPU is actually the same as 500 mCPU.

**To Reproduce**
1. Deploy a pod with 500 CPU resource limit or required value
2. Sync and observe the sync loop
3. Go to the diff tab of the deployment and observe the difference.

**Expected behavior**
ArgoCD should recognize that the 500 mCPU and the 0.5 CPU are actually the same values.

**Screenshots**
![image](https://github.com/argoproj-labs/argocd-operator/assets/2914096/3f62a62e-ec6e-4490-a3a8-df3402b7553e)

**Additional context**
- Observed with v2.10.4+f5d63a5
- ArgoCD gets stuck in a sync loop, since it thinks that the deployed manifest is not in sync and keeps on re-applying the manifest. [NOK]

**Comment by anandf** [comment]
This should be an issue created in ArgoCD project https://github.com/argoproj/argo-cd. Does `kubectl diff` command work as expected ?

**Comment by 4TT1L4** [comment]
> This should be an issue created in ArgoCD project https://github.com/argoproj/argo-cd

Can you move it there or I need to close it and create a new one in the correct repostory?

**Comment by svghadi** [comment]
@4TT1L4 - You can close this one and create a new one in https://github.com/argoproj/argo-cd

**Comment by 4TT1L4** [comment]
As suggested above;
 - I have created a new issue:
   - https://github.com/argoproj/argo-cd/issues/17682
 - And I am closing this one.
