### ISSUE TITLE
Add possibility to change haproxy image

### ISSUE THREAD

**Issue by ccdgrundhoefer** [argoproj-labs/argocd-operator#131]
Hello,

it seems, that you can change all images via the ArgoCD CRD except for the redis haproxy image, which is unfortunate in a disconnected environment.
Is it possible to add support for this?

**Comment by jmckind** [comment]
Hey @ccdgrundhoefer, thanks for trying the operator. This can be added, sorry for the oversight on that image

**Comment by jmckind** [comment]
Merged into master and will go out in v0.0.13
