### ISSUE TITLE
New NotificationsConfiguration CRD misses context option

### ISSUE THREAD

**Issue by GijsvanDulmen** [argoproj-labs/argocd-operator#1320]
**Describe the bug**
The argocd notifications configmap has an option to provide context variables for usage in templates.
This is not possible through the NotificationsConfiguration since the update. I consider this a regression/omission therefore reported as bug.

**To Reproduce**
See description.

**Expected behavior**
Have an option in the CR to also provide context. Could be a simple field which maps towards the configmap.

**Comment by saumeya** [comment]
Hi, this issue is fixed - https://github.com/argoproj-labs/argocd-operator/pull/1305

**Comment by GijsvanDulmen** [comment]
@saumeya Ah! Did not notice this change. Thanks for the reference. Will close this.
