### ISSUE TITLE
RFE: Support for disabling Dex

### ISSUE THREAD

**Issue by lhw** [argoproj-labs/argocd-operator#142]
As ArgoCD works quite well with already existing OIDC providers it would be nice to have the option to completely disable the deployment of the bundled Dex server.

**Comment by jmckind** [comment]
Thanks for the suggestion @lhw! That is something that I also noticed in the past and meant to come back to fix.

**Comment by tylerauerbeck** [comment]
@iam-veeramalla I believe this can be done with the `DISABLE_DEX` var correct? So I think this issue can be closed.

**Comment by iam-veeramalla** [comment]
> @iam-veeramalla I believe this can be done with the `DISABLE_DEX` var correct? So I think this issue can be closed.

Thanks @tylerauerbeck  .. true.

**Comment by Morriz** [comment]
Can this be re-opened? The var is not working and we see dex deployed.
