### ISSUE TITLE
[v0.11.0] argocd-operator deployment fails with PodSecurity "restricted:latest", seccompProfile missing

### ISSUE THREAD

**Issue by hamidos** [argoproj-labs/argocd-operator#1492]
**Describe the bug**

Deploying the argocd-operator fails in a Kubernetes cluster with the PodSecurity policy "restricted:latest" enabled. 
The error message indicates a violation due to the missing securityContext.seccompProfile.type in the manager container.

```
LAST SEEN   TYPE    REASON        OBJECT                                                   MESSAGE
4m35s       Warning FailedCreate  replicaset/argocd-operator-controller-manager-6855dff84f Error creating: pods "argocd-operator-controller-manager-6855dff84f-wmqrn" is forbidden: violates PodSecurity "restricted:latest": seccompProfile (pod or container "manager" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

**To Reproduce**
1. Apply Pod Security Standards restricted at [the Cluster Level](https://kubernetes.io/docs/tutorials/security/cluster-level-pss/) or at [ the Namespace](https://kubernetes.io/docs/tutorials/security/ns-level-pss/) where the operator is going to be installed
2. Follow the installation [documentation](https://argocd-operator.readthedocs.io/en/latest/install/olm/)

**Expected behavior**
argocd-operator should deploy successfully without violating the "restricted:latest" PodSecurity policy.

**Comment by svghadi** [comment]
Did you encounter similar errors for any of argocd-operator component deployments like redis, dex, appset, etc?

**Comment by hamidos** [comment]
Hello @svghadi , 
After further testing, the appset and dex deployments reported similar errors.  
Adding the `seccompProfile` to those Pods addressed the issue.
