### ISSUE TITLE
Cannot disconnect a repository with a wrong URL

### ISSUE THREAD

**Issue by mbrozzo** [argoproj-labs/argocd-operator#1497]
**Describe the bug**
I have connected a SSH repository with a wrong URL in ArgoCD (I left "git clone" in the URL) and now when I click "Disconnect" I only get this error in the UI:
`Unable to disconnect repository: repo 'git clone git@[ADDRESS].git' not found`

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Connect Repo'
3. In the field "Repository URL" put a string with this format: "git clone git@[ADDRESS].git"
4. Fill the other fields
5. Connect the repo
6. In the list of repositories, click the three dots on the right of the newly created repo
7. Click "Disconnect"
8. See the error

**Expected behavior**
The repository is disconnected.

**Screenshots**
![image](https://github.com/user-attachments/assets/8f1476f0-aa20-46c8-af70-5fc971c0400d)
![image](https://github.com/user-attachments/assets/7cbe44db-631e-4a15-8637-55f5e4cbb6c2)

**Additional context**
I am using the ArgoCD operator in OKD.

P.S.: I would appreciate if there was a workaround in the mean time.

**Comment by svghadi** [comment]
Hi @mbrozzo, you can manually delete the wrong repo from cluster by deleting the repo secret. Look for secrets with name `repo<some number>` in your ArgoCD instance namespace and inspect the url in them to identify the correct one to delete.

As for the bug, I could reproduce it but I believe it is a upstream Argo CD bug as operator doesn't handle repository object. Please create a bug issue in [argoproj/argo-cd](https://github.com/argoproj/argo-cd) upstream project.

**Comment by mbrozzo** [comment]
Hi @svghadi thank you very much, I was able to find and remove the secret, and the repo also disappeared from the UI. There is an open issue already on their GithHub, I will point out that, although I solved it, it is a problem on their side.

**Comment by svghadi** [comment]
Yeah, we can close this and track the bug in Argo CD project.

**Comment by lamnguyenx** [comment]
> Hi [@mbrozzo](https://github.com/mbrozzo), you can manually delete the wrong repo from cluster by deleting the repo secret. Look for secrets with name `repo<some number>` in your ArgoCD instance namespace and inspect the url in them to identify the correct one to delete.
> 
> As for the bug, I could reproduce it but I believe it is a upstream Argo CD bug as operator doesn't handle repository object. Can you create a bug issue in [argoproj/argo-cd](https://github.com/argoproj/argo-cd) upstream project?


I'm using AgroCD v3.0.6+db93798 with Rancher v2.9.1 and your solution worked!
