### ISSUE TITLE
Invalid image digest for OLM catalog deployment (release-0.12)

### ISSUE THREAD

**Issue by bendudz** [argoproj-labs/argocd-operator#1548]
**Describe the bug**
When installing the ArgoCD Operator via OLM, the docker image digest that is required by the OLM install plan is invalid.

**To Reproduce**
Following [this](https://argocd-operator.readthedocs.io/en/latest/install/olm/) guide, assuming you have OLM setup in Kubernetes when adding a subscription to the `release-0.12` version of argocd-operator the image digest of the operator is incorrect. 

Install ArgoCD Operator into OLM:
```shell
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj-labs/argocd-operator/refs/heads/release-0.12/deploy/catalog_source.yaml
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj-labs/argocd-operator/refs/heads/release-0.12/deploy/operator_group.yaml
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj-labs/argocd-operator/refs/heads/release-0.12/deploy/subscription.yaml
```

Wait for the install plan to start `kubectl get install plans -n argocd`.

A deployment will appear in the argocd namespace which can't create the pod due to 'invalid checksum digest length'.

The image its trying to create the pod with is: `quay.io/argoprojlabs/argocd-operator@sha256:405e7bde25affb7644c576a7f2d41ba30b88e2ef4f2f11945b920a33517895cee`

However the image available in quay [here](https://quay.io/repository/argoprojlabs/argocd-operator/manifest/sha256:405e7bde25affb7644c576a7f2d41ba30b88e2ef4f2f11945b920a33517895ce) is `quay.io/argoprojlabs/argocd-operator@sha256:405e7bde25affb7644c576a7f2d41ba30b88e2ef4f2f11945b920a33517895ce` notice the last 'e' is missing.

**Expected behavior**
I'd expect the ArgoCD Operator to be able to be deployed via OLM without error.

The digest causing the issue is hardcoded here: https://github.com/argoproj-labs/argocd-operator/blob/403e0863849cfb89782fb559dae7d4ff679a4357/deploy/olm-catalog/argocd-operator/0.12.0/argocd-operator.v0.12.0.clusterserviceversion.yaml#L1904

On the surface it's a simple typo to fix but I was unsure if this is caused by your build process otherwise I'd have offered a PR to fix. If you can advise I'll create a fix for it. Thanks

**Comment by saumeya** [comment]
Thanks @bendudz  for catching this, it is indeed a typo and is not caused due to build process. I have created a fix here - https://github.com/argoproj-labs/argocd-operator/pull/1549 . Once it is merged, please try again and it should work.

**Comment by bendudz** [comment]
Hi, it's still got the same issue. I did see another 2 occurrences in the [release](https://github.com/argoproj-labs/argocd-operator/pull/1522/files) but unsure what they are used for.

[Here](https://github.com/argoproj-labs/argocd-operator/blob/release-0.12/bundle/manifests/argocd-operator.clusterserviceversion.yaml#L1904)
[Here](https://github.com/argoproj-labs/argocd-operator/blob/release-0.12/config/manager/kustomization.yaml#L14)

Just copied the bundles.db out of the catalog container and can see the `...95cee` digest in there. Will [this](https://github.com/argoproj-labs/argocd-operator/blob/release-0.12/deploy/catalog_source.yaml#L7C10-L7C127) image require a rebuild?

**Comment by saumeya** [comment]
Thanks for the prompt response, taking a look at this.

**Comment by saumeya** [comment]
@bendudz it is fixed now

**Comment by bendudz** [comment]
Hi @saumeya i can confirm it’s working. Thank you
