### ISSUE TITLE
The Custom fields in the ArgoCD Edit form section changes focus to Prometheus section size field 

### ISSUE THREAD

**Issue by JTG2020** [argoproj-labs/argocd-operator#21]
Installed operator successfully in OpenShift V4. When I tried to create instance of ArgoCD and clicked on the Edit form to update some of the configurations e.g. when I try to change the application name, the cursor changes the focus to Prometheus section "size" field. Currently Edit Form is unusable. Can someone please take a look ?
Thanks

**Comment by jmckind** [comment]
Thanks @JTG2020, will be making changes to clean up the issues with the Edit Form. Can you let me know the minor version of OpenShift that you are on? Example: 4.2 or 4.3

**Comment by JTG2020** [comment]
Using openshift 4.2.12

**Comment by jmckind** [comment]
@JTG2020, I have made some modifications to the CSV to fix the Edit Form on OpenShift 4.x, as well as to add all of the currently available properties for the ArgoCD resource. This will be a part of the v0.0.5 release going out this week.

**Comment by jmckind** [comment]
Released as part of v0.0.5.
