### ISSUE TITLE
Delete old versions of olm-catalog ?

### ISSUE THREAD

**Issue by iam-veeramalla** [argoproj-labs/argocd-operator#308]
### Is your task related to a problem? Please describe.
Can we delete the old versions of olm-catalog ? we currently have versions from 0.0.2 to 0.0.15

### Describe the solution you'd like
Delete old versions. Probably maintain last 3 if required ?

### Describe alternatives you've considered
NA

### Additional context
NA

**Comment by iam-veeramalla** [comment]
@wtam2018 will this be removed as part of operator-sdk update ? or is there a specific reason why we are maintaining so many versions ?

**Comment by wtam2018** [comment]
@iam-veeramalla  They will be removed as part of operator-sdk upgrade.

**Comment by iam-veeramalla** [comment]
Thanks @wtam2018
