### ISSUE TITLE
Tolerations & nodeselectors in argocd CRD.

### ISSUE THREAD

**Issue by GrataHonoria** [argoproj-labs/argocd-operator#342]
**Describe the bug**
I can't seem to find a way to add toleration's & node-selectors to the pods that the operator deploys, I can add toleration's to the operator pod but not sure how to do it for the other pods.

**To Reproduce**
Look at operator docs & API spec.
Write an argocd resource.

**Expected behavior**
A option in the argocd resource definition for toleration's & node-selector

**Screenshots**
N\A

**Additional context**
For now I patch the deployments with the toleration's & node-selectors after the pods have been deployed, they seem to get moved to the right nodes.
Since I'm using a cloud based Kubernetes cluster I'm unable to set the podtolerationrestriction admission controller.

**Comment by saumeya** [comment]
Please assign this to me
