### ISSUE TITLE
ApplicationSet controller Crashloopbackoff

### ISSUE THREAD

**Issue by iam-veeramalla** [argoproj-labs/argocd-operator#403]
**Describe the bug**
I noticed a crashloopbackoff on the ApplicationSet controller. Pasting the error logs for analysis.
```
flag provided but not defined: -loglevel
Usage of applicationset-controller:
  -argocd-repo-server string
    	Argo CD repo server address (default "argocd-repo-server:8081")
  -debug
    	Print debug logs
  -dry-run
    	Enable dry run mode
  -enable-leader-election
    	Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager.
  -kubeconfig string
    	Paths to a kubeconfig. Only required if out-of-cluster.
  -metrics-addr string
    	The address the metric endpoint binds to. (default ":8080")
  -namespace string
    	Argo CD repo namespace (default: argocd)
  -policy string
    	Modify how application is synced between the generator and the cluster. Default is 'sync' (create & update & delete), options: 'create-only', 'create-update' (no deletion) (default "sync")
  -probe-addr string
    	The address the probe endpoint binds to. (default ":8081")
``` 

**To Reproduce**
1. run the operator locally using `operator-sdk run local`

**Expected behavior**
No pods should run into backoff or error state.

**Additional context**
NA

**Comment by iam-veeramalla** [comment]
@tylerauerbeck I think this is introduced due to #371 . Can you please verify ?

**Comment by tylerauerbeck** [comment]
@iam-veeramalla Yepp, that's what did it. Just confirmed what's going on. Looks like the version of the applicationset-controller that is used in the operator by default doesn't have the `loglevel` flag. Does it make more sense to bump the version? Or remove the functionality for now?

**Comment by iam-veeramalla** [comment]
> @iam-veeramalla Yepp, that's what did it. Just confirmed what's going on. Looks like the version of the applicationset-controller that is used in the operator by default doesn't have the `loglevel` flag. Does it make more sense to bump the version? Or remove the functionality for now?

@jgwest would be the best person to help us in this

**Comment by jgwest** [comment]
Yup, log level is not in ApplicationSet v0.1.0, it was added in v0.2.0 as part of https://github.com/argoproj-labs/applicationset/pull/249. So the loglevel flag would be invalid until argocd-operator picks up v0.2.0 of AppSets.

**Comment by iam-veeramalla** [comment]
> Yup, log level is not in ApplicationSet v0.1.0, it was added in v0.2.0 as part of [argoproj-labs/applicationset#249](https://github.com/argoproj-labs/applicationset/pull/249). So the loglevel flag would be invalid until argocd-operator picks up v0.2.0 of AppSets.

Does v0.2.0 only work with the latest Argo CD release v2.1.0 ?

**Comment by jgwest** [comment]
@iam-veeramalla ApplicationSet v0.2.0 should work with both Argo CD v2.0 and v2.1 (and should also work with previous versions too, but I have not tested here recently.)
