### ISSUE TITLE
update operator-sdk version in the go.mod

### ISSUE THREAD

**Issue by iam-veeramalla** [argoproj-labs/argocd-operator#461]
**Describe the bug**
`operator-sdk` version in the go.mod is very old. We need to update it to `v1.11.0`. Operator prints the sdk version using this dependency which will create a confusion to the users about the sdk version being used.

While it looks simple and straight forward, it is slightly complicated. The new version of operator-sdk has structural changes w.r.t to packages. Some of the packages like `k8sutil` which is used by the `argocd-operator` no longer exists in the new version of `operator-sdk`. It is an internal package in the new version.
Reference:
https://github.com/operator-framework/operator-sdk/issues/3792

**Expected behavior**
Update the `operator-sdk` version

**Comment by Elyytscha** [comment]
I added a PR for this, checks are passing, Feedback would be nice

**Comment by Elyytscha** [comment]
@svghadi maybe we can work this out together too? :) would be willing to help with this, an initial pr i already submitted, but i think its not ready yet

**Comment by svghadi** [comment]
Sure @Elyytscha. Allow me some time to go through the issue and your PR.

**Comment by Elyytscha** [comment]
Hello, as I saw https://github.com/argoproj-labs/argocd-operator/pull/1447/files is merged already.

What i wanted to add is that memory limit of 128 MB is a little bit low as the argocd operator runs already with 116 MB of Memory in my environment and I dont utilize the operator that much. Would recommend to set it at least to 256 MB to be safe so a loaded argocd operator wouldn't crash with oom.

![image](https://github.com/user-attachments/assets/64c9de55-936b-49ab-bd72-81b78d973c4d)
https://github.com/saumeya/argocd-operator/blob/e95479589154094614e5bb4ec000e37e98f2e27e/config/default/manager_auth_proxy_patch.yaml#L17

@saumeya @svghadi

**Comment by svghadi** [comment]
Hi @Elyytscha, the resource limits are applied for `kube-rbac-proxy`  container only 
https://github.com/argoproj-labs/argocd-operator/blob/a82719a1fce8c6fb3c7afea48afddc6d803bce53/config/default/manager_auth_proxy_patch.yaml#L12-L20
So I don't think they will be impacting `manager` container resources which is where operator code runs. 

Can you check the `kube-rbac-proxy` container resource usage in your env? If the utilisation is near to limits set, we can discuss on bumping it up.

**Comment by Elyytscha** [comment]
Oh that I have overlooked 0.10.1 (where I am on right now) seems to not have a kube-rbac-proxy so I cant see the mem usage there, but it should be fine i think.

I can look up the mem usage effortlessly when 0.11.0 is available over here https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/argocd-operator

**Comment by svghadi** [comment]
The operator-sdk has been upgraded to 1.35 with #1447, #1449 & #1462. Thanks @LaloLoop & @Elyytscha for the initial work. It really helped a lot.
