### ISSUE TITLE
manual install and kustomize docs are wrong

### ISSUE THREAD

**Issue by Kampe** [argoproj-labs/argocd-operator#470]
`deploy/` directory has nothing but operator yaml in it now.

**Comment by tylerauerbeck** [comment]
@iam-veeramalla I don't believe I see any instructions that reference the `/deploy` directory any longer. Looks to have been replaced with `make deploy` and `make deploy IMG=quay.io/my-org/argocd-operator:latest`. So I believe this can be closed?

**Comment by iam-veeramalla** [comment]
@tylerauerbeck .. Yes, docs are updated by @jopit . Thanks for noticing this.
