### ISSUE TITLE
Add support for `globalProjects` in `argocd-cm`

### ISSUE THREAD

**Issue by jyniybinc** [argoproj-labs/argocd-operator#481]
It would be great if the new `globalProjects` feature were supported:
https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#configuring-global-projects-v18

**Comment by iam-veeramalla** [comment]
Hi @hzliangbin , Thanks for accepting to work on the issue.

**Comment by iam-veeramalla** [comment]
Hi @hzliangbin did you get chance to work on this one ?

**Comment by hzliangbin** [comment]
@iam-veeramalla  sorry...just got busy recently

**Comment by iam-veeramalla** [comment]
@hzliangbin np :) .. please let us know if you are  still interested in getting this done

**Comment by hzliangbin** [comment]
@iam-veeramalla adding help-wanted label would be fine...

**Comment by iam-veeramalla** [comment]
This feature is implemented as part of #642
