### ISSUE TITLE
When multiple envs are merged, the pods may be coordinated many times due to unsorted

### ISSUE THREAD

**Issue by muicoder** [argoproj-labs/argocd-operator#496]
**Describe the bug**

argocd-operator: v0.1.0

**Fixed**
https://github.com/argoproj-labs/argocd-operator/pull/495
> ### Looking forward to a better env sorting method

**Comment by iam-veeramalla** [comment]
will be fixed by #467 or #495

**Comment by iam-veeramalla** [comment]
fixed in latest.
