### ISSUE TITLE
Using the volumes, volumeMounts and initContainers fields in the repo server is invalid

### ISSUE THREAD

**Issue by muicoder** [argoproj-labs/argocd-operator#497]
**Describe the bug**

argocd-operator: v0.1.0

After the volumes, volumeMounts and initContainers fields are invalid in the repo server, the remaining coordination tasks can be completed through the following pr modification.

### > https://github.com/argoproj-labs/argocd-operator/pull/494

**Comment by iam-veeramalla** [comment]
will be fixed by #467

**Comment by iam-veeramalla** [comment]
@muicoder Thanks for raising issue with us. Can you please provide more information on this ?
