### ISSUE TITLE
Can't override hostname for route

### ISSUE THREAD

**Issue by wrichter** [argoproj-labs/argocd-operator#56]
due to #54 I renamed my ArgoCD instance from "argocd" to "argocdinstance". This then causes the default route hostname to change from argocd-server-argocd.apps.my.cluster to argocdinstance-server-argocd.apps.my.cluster. According to the [docs](https://argocd-operator.readthedocs.io/en/latest/reference/argocd/#server-options), it should be possible to set the route hostname via spec.server.host, but this doesn't seem to impact the hostname of the exposed route.

**Comment by jmckind** [comment]
Thanks for pointing this out @wrichter, I have a fix for this in the works.

**Comment by wrichter** [comment]
Thanks by the way for the awesome operator :-)

**Comment by jmckind** [comment]
Thanks for the kind words! I just merged #58 that will fix the issue that forced you to change the name of the cluster. Using `argocd` for the cluster name will be supported once again. In addion to that I am working on fixing the issue that prevents overriding the hostname on the Route.

**Comment by jmckind** [comment]
Released in v0.0.8
