### ISSUE TITLE
Requesting to support latest version of argocd installation using operator

### ISSUE THREAD

**Issue by kmanchik** [argoproj-labs/argocd-operator#565]
### Is your task related to a problem? Please describe.

- As we already there is an Argo CD High Severity Vulnerability and its impact on Kubernetes and fixes are available in the 

   https://apiiro.com/blog/malicious-kubernetes-helm-charts-can-be-used-to-steal-sensitive-information-from-argo-cd-deployments/

### Describe the solution you'd like

-. [A patch](https://github.com/argoproj/argo-cd/security/advisories/GHSA-63qx-x74g-jcr7) is available for Argo CD versions:

v2.3.0
v2.2.4
v2.1.9

-Upgrading the operator to support would help to avoid Vulnerability

### Describe alternatives you've considered

- We can point to a fixed image, but it would be ideal to update using operator.

**Comment by iam-veeramalla** [comment]
latest version of the operator install v2.2.5.
