### ISSUE TITLE
Add ingressClassName field

### ISSUE THREAD

**Issue by adubkov** [argoproj-labs/argocd-operator#652]
We need to add `ingressClassName` support to customize ingress.

**Comment by adubkov** [comment]
and `host`

**Comment by ishitasequeira** [comment]
Hi @adubkov, I guess this [PR](https://github.com/argoproj-labs/argocd-operator/pull/636/) might suffice the request. WDYT?

**Comment by adubkov** [comment]
@ishitasequeira Yes, it looks like it would solve this issue.

**Comment by ishitasequeira** [comment]
closing this as its a duplicate of [626](https://github.com/argoproj-labs/argocd-operator/issues/626)
