### ISSUE TITLE
Invalid Credentials Generated

### ISSUE THREAD

**Issue by NormJohnIV** [argoproj-labs/argocd-operator#78]
On a fresh install using the olm we cannot access argo via the ui or cli. All attempts respond with incorrect credentials. Checking the events and watching as the deployments come up we are positive this is the first container and not a recreated container. So, following this guide https://argoproj.github.io/argo-cd/faq/#i-forgot-the-admin-password-how-do-i-reset-it, we reset the password. No change. So, we also try deleting the admin.password and admin.passwordMtime as noted in the guide. This causes a new container to be create and the secret update with new credentials. We try logging in again with both the old pod and new pod name to no avail. We even tried to use the terminal in the pod to login thus ensuring the ingress was doing something weird. Again not success. Any assistance would be much appreciated.

**Comment by NormJohnIV** [comment]
After further testing and troubleshooting we found that a change was made 14 days ago and the password is both neither the pod name nor stored in the argocd-secret secret. Instead, the password in now a randomly generated password that is stored in a new secret named argocd-cluster. https://github.com/argoproj-labs/argocd-operator/commit/80bd11aacb1ff26979653f71d58b8700bd15af9b . This was quite confusing and the docs should be updated to reflect this change.

**Comment by gregsheremeta** [comment]
thanks @NormJohnIV. Indeed this did it for me too. I was able to login with the password here:
`oc get secret argocd-cluster -o yaml | yq r - "data.admin*" | base64 --decode`

**Comment by Aenima4six2** [comment]
So can we get the docs updated? This just cost me four hours of pain.
https://argocd-operator.readthedocs.io/en/latest/usage/basics/#secrets
