### ISSUE TITLE
How do you set users.session.duration?

### ISSUE THREAD

**Issue by rcfja** [argoproj-labs/argocd-operator#783]
How do I edit users.session.duration? 

If I edit argocd-cm directly, any changes are reverted immediately by openshift.

**Comment by iam-veeramalla** [comment]
Hi @rcfja , sorry for getting back late on this one. 

Yes, any manual changes to the Argo CD Config map are reverted back by the operator. You can make use of the extraConfig feild in the Argo CD CR.
https://argocd-operator.readthedocs.io/en/latest/usage/extra-config/

**Comment by rcfja** [comment]
thank you!
