### ISSUE TITLE
Provide a way to pass extra arguments in ArgoCD application controller.

### ISSUE THREAD

**Issue by samsingh26** [argoproj-labs/argocd-operator#859]
**Is your feature request related to a problem? Please describe.**

ArgoCD application controller has the option to expose application labels in Prometheus metric using "--metrics-appication-labels" as mentioned in this document (https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/metrics.md). According to the documentation, this requires extra parameters to be provided to argocd-application-controller. When using the operator the StatefulSet for the controller is managed by the operator, hence it's not possible to add the aforementioned parameters.

So can anyone please help me to understand if is there any way by which I can pass metrics application argument in argocd-application-controller.

**Comment by svghadi** [comment]
Hi @samsingh26, #1474 implemented this functionality. A new `.spec.controller.extraCommandArgs ` field is added in `ArgoCD` CR to support additional cli arguments to `argocd-application-controller` deployment. The feature will be available to users in upcoming **ArgoCD Operator v0.12.0** release. You can find the documentation [here](https://argocd-operator.readthedocs.io/en/latest/reference/argocd/#controller-options).
