### ISSUE TITLE
Q: How to create Datadog annotations when using ArgoCD from the operator

### ISSUE THREAD

**Issue by Unfaced85** [argoproj-labs/argocd-operator#861]
We are using the argocd-opertator and are quite happy with it. I want to set these annotation https://docs.datadoghq.com/integrations/argocd/ according to datadog docu, but how do I do that using the operator? 

We use some settings with using the argocd-cmd-params-cm configmap, but I did not find any hints in the docu how I could set annotations there, same in the crd of the operator.

Any input on how to properly do it is appreciated, thanks.

**Comment by matthewhembree** [comment]
I was wondering the same. Doesn't seem possible. #637

**Comment by Unfaced85** [comment]
I see, that is unfortunate. In that case I think I need to see how I can resolve this for my team.

**Comment by matthewhembree** [comment]
I think it would be possible to mutate the Pod/Deployments with a Kyverno policy. It doesn't seem that the operator's reconciliation controller is interested in the annotations field.

It does, however, appear that the reconciler is [interested](https://github.com/argoproj-labs/argocd-operator/blob/master/controllers/argocd/statefulset.go#L136) in the annotations of the Redis HA StatefulSet.

**Comment by svghadi** [comment]
Hi @AlexanderWurz , @matthewhembree, 
#1532 implemented support to add custom annotations and labels on Argo CD component pods created by Operator. New fields are introduced in `ArgoCD` CR to support this. Refer https://github.com/argoproj-labs/argocd-operator/blob/master/docs/usage/custom_labels_annotations.md  for more details. 

 It will be available in **upcoming 0.13.0 release** .

**Comment by svghadi** [comment]
I am closing this issue. Please feel free to reopen if the new feature doesn't help with your use case.
