### ISSUE TITLE
Operator Version 0.6.0 is not part of redhat-openshift community-operators

### ISSUE THREAD

**Issue by bo0ts** [argoproj-labs/argocd-operator#897]
The new operator version is not yet part of the openshift community-operators index. It used to be available there as well and should be updated to the most recent version.

**Comment by iam-veeramalla** [comment]
Hi @bo0ts , I requested the team to merge 
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/2542

**Comment by bo0ts** [comment]
@iam-veeramalla I doubt this will ever get merged as long as 4.8 is not supported, which is a real problem since this breaks updates for almost all OpenShift users.

**Comment by jonaslar** [comment]
Hi, I just noticed the PR in redhat-openshift-ecosystem/communti-operators-prod-repo regarding argocd-operator release 0.6.0 was closed.

Will we see 0.6.0 in OpenShift OperatorHub?

**Comment by bo0ts** [comment]
@jonaslar I don't think so, the new PR is still not there.

**Comment by bo0ts** [comment]
4.8 is not supported anymore
