### ISSUE TITLE
How to upgrade Operator and then ArgoCD

### ISSUE THREAD

**Issue by bortek** [argoproj-labs/argocd-operator#92]
Hi guys!

I am looking through the documentation but cannot find the answer. ArgoCD operator in my cluster is v 0.0.8 while there is a newer version 0.0.9. 

At the same time ArgoCD version out there is 1.5.5 while the one that operator is running is 1.5.1.

Operator says everything is up to date.

How do I make the operator update ArgoCD to newer version?

**Comment by jmckind** [comment]
Hi @bortek, did you install the operator through OLM or manually using the manifests in the `deploy` directory?

**Comment by bortek** [comment]
Well I have figured it out, turns out it was not installed as an operator but manually. :(  Thanks for responding.

**Comment by robertodocampo** [comment]
I have the same problem (i installed the operator through OLM). May be possible that the 0.0.9 was not published on the community-operators? (I'm using openshift 4.4)

Regards

**Comment by jmckind** [comment]
@robertodocampo The PR was merged at the end of last week for the v0.0.9 operator in the community operators (OpenShift Operator Hub), so it should show there soon.

**Comment by robertodocampo** [comment]
Thanks a lot @jmckind ! The operator was upgraded to the 0.0.9 version this morning. However the argocd was not upgraded. I need to do something more? I usually rely on the automatic operators to do this upgrades ("full cycle operators")

Regards
